workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    edc:
        inputs:
            - location: registry.speakeasyapi.dev/edc/plexapi/plexapi:main
targets:
    plexjs:
        target: typescript
        source: edc
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/edc/plexapi/code-samples-typescript-plexjs
